# tasks file for postfix
---
- name: configure debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ postfix_debconf_selections }}"
  tags:
    - postfix-config
    - postfix
    - postfix-install

- name: install package
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ postfix_install }}"
  tags:
    - postfix-config
    - postfix
    - postfix-install

- name: configure mailname
  template:
    src: etc/mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: reconfig postfix
  tags:
    - postfix-config
    - postfix
    - postfix-mailname

# Include main.cf task file
- include: main-cf.yml

- name: configure sasl username/password
  template:
    src: etc/postfix/sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  when: postfix_relayhost != false
  no_log: true
  notify:
    - postmap sasl_passwd
    - reconfig postfix
  tags:
    - postfix-config
    - postfix
    - postfix-sasl-passwd

- name: configure aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.user }}:.*'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_aliases }}"
  notify:
    - new aliases
  tags:
    - postfix-config
    - postfix
    - postfix-aliases

- name: configure virtual aliases
  lineinfile:
    dest: /etc/postfix/virtual
    regexp: '^{{ item.virtual }}.*'
    line: '{{ item.virtual }} {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_virtual_aliases }}"
  notify:
    - new virtual aliases
  tags:
    - postfix-config
    - postfix
    - postfix-virtual-aliases

- name: configure sender canonical maps
  lineinfile:
    dest: /etc/postfix/sender_canonical_maps
    regexp: '^{{ item.sender }}.*'
    line: '{{ item.sender }} {{ item.rewrite }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_sender_canonical_maps }}"
  notify:
    - postmap sender_canonical_maps
  tags:
    - postfix-config
    - postfix
    - postfix-sender-canonical-maps

- name: configure generic table
  lineinfile:
    dest: /etc/postfix/generic
    regexp: '^{{ item.pattern }}.*'
    line: '{{ item.pattern }} {{ item.result }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_generic }}"
  notify:
    - postmap generic
  tags:
    - postfix-config
    - postfix
    - postfix-generic-table

