# handlers file for postfix
---
- name: new aliases
  command: newaliases

- name: new virtual aliases
  command: postmap hash:/etc/postfix/virtual

- name: postmap sasl_password_maps
  command: postmap hash:/etc/postfix/sasl_password_maps

- name: postmap sender_canonical_maps
  command: postmap hash:/etc/postfix/sender_canonical_maps

- name: postmap generic
  command: postmap hash:/etc/postfix/generic

- name: reconfig postfix
  service:
    name: postfix
    state: reloaded
